### PR TITLE
Handle organization sponsor entity

### LINKED ISSUE #31: Sponsor from org is not processed
Hi,

First of all thanks for this lib. I use it through your `readme-scribe` action and it works pretty well except for one thing. If an org sponsors me, the [User entity](https://github.com/crazy-max/crazy-max/blob/f8716d665bf3f08dd6863172a9515885d2f0122b/templates/README.md.tpl#L21) is empty and so displayed as anonymous on my readme.

I think you have to take into account the [Organization object](https://docs.github.com/en/graphql/reference/objects#organization) in the [Sponsor entity](https://docs.github.com/en/graphql/reference/unions#sponsor).

### PR DESCRIPTION
**Pull request by crazy-max**
Fixes #31

```graphql
{
  user(login: "crazy-max") {
    login
    sponsorshipsAsMaintainer(first: 100) {
      totalCount
      edges {
        cursor
        node {
          createdAt
          sponsorEntity {
            __typename
            ... on User {
              login
              name
              avatarUrl
              url
            }
            ... on Organization {
              login
              name
              avatarUrl
              url
            }
          }
        }
      }
    }
  }
}
```

```text
{{- range sponsors 10 }}
- {{ if (eq .User.Name "") }}_Anonymous_{{ else }}[{{ .User.Name }}]({{ .User.URL }}){{ end }} ({{ humanize .CreatedAt }})
{{- end }}
```

```text
- [prompt](https://github.com/pr-mpt) (2 days ago)
- [Chris Nesbitt-Smith](https://github.com/chrisns) (1 month ago)
- [Nick Sweeting](https://github.com/pirate) (2 months ago)
- [LitoMore](https://github.com/LitoMore) (2 months ago)
- [Max Schoening](https://github.com/max) (2 months ago)
- [dy](https://github.com/dyipon) (2 months ago)
- [Bret Fisher](https://github.com/BretFisher) (2 months ago)
- [Nat Friedman](https://github.com/nat) (2 months ago)
- _Anonymous_ (3 months ago)
- [Yumin Wong](https://github.com/itsbagpack) (6 months ago)
```

cc @muesli

### CODE REVIEW

**Comment by muesli** [comment]
> ```
> {{- range sponsors 10 }}
> - {{ if (eq .User.Name "") }}_Anonymous_{{ else }}[{{ .User.Name }}]({{ .User.URL }}){{ end }} ({{ humanize .CreatedAt }})
> {{- end }}
> ```

Just to understand this correctly: in which situations do we expect an empty username here? When the sponsor opts to stay anonymous?

This might be something we want to adjust in the example template.

**Comment by crazy-max** [comment]
@muesli 

> Just to understand this correctly: in which situations do we expect an empty username here? When the sponsor opts to stay anonymous?

When it's a private sponsor, `name` is _null_:

```json
{
  "data": {
    "user": {
      "login": "crazy-max",
      "sponsorshipsAsMaintainer": {
        "totalCount": 19,
        "edges": [
          {
            "cursor": "MTU",
            "node": {
              "createdAt": "2021-02-12T11:04:19Z",
              "sponsorEntity": {
                "__typename": "User",
                "login": "<redacted>",
                "name": null,
                "avatarUrl": "<redacted>",
                "url": "<redacted>"
              }
            }
          }
        ]
      }
    }
  }
}
```

**Comment by muesli** [comment]
Thank you, @crazy-max!

**Comment by muesli** [comment]
I just realized there's one potential issue: this call now requires a new permission on the token: `read:org`.

We'll have to make sure to somehow notify users of markscribe or its GitHub Action.

**Comment by crazy-max** [comment]
@muesli 

> I just realized there's one potential issue: this call now requires a new permission on the token: `read:org`.

Ah yes that's right completely forgot to tell you this.

**Comment by crazy-max** [comment]
```text
$ markscribe -write test.txt template.tpl
Can't render template: template: tpl:20:10: executing "tpl" at <sponsors 15>: error calling sponsors: Your token has not been granted the required scopes to execute this query. The 'login' field requires one of the following scopes: ['read:org'], but your token has only been granted the: ['read:user', 'repo', 'workflow'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
```

I think this error message is enough. WDYT?

**Comment by muesli** [comment]
> I think this error message is enough. WDYT?

For markscribe itself, certainly. For the GitHub Action it's not exactly ideal, but I guess it's the best "notification" we got currently.

**Comment by crazy-max** [comment]
@muesli Any ETA for next release? Thanks.

**Comment by muesli** [comment]
Now :smile: v0.6.0 is out!

**Pull request merged**
