### PR TITLE
Allow HTML comments to be generated

### LINKED ISSUE #62: HTML comments are removed
When using `markscribe` all HTML comments are removed. However, in certain cases a user still wants to keep HTML comments as part of the output of the templating.

Desired fix:
Provide a way so that HTML comments are still shown in the generated file.

### PR DESCRIPTION
**Pull request by jetzlstorfer**
closes #62 and allows to define HTML comments that will be part of the generated file

### CODE REVIEW

**Comment by muesli** [comment]
I think I would expect a `comment` method to automatically apply the comment markup. The problem here is that there's no official standard for markdown (CommonMark standard) comments.

Raw HTML comments can already be added to a template without the need for a helper method.

**Comment by jetzlstorfer** [comment]
Hi @muesli exactly the second point - HTML comments - are the reason for my PR. 
Here is what happens:

I take the current version of the master branch and run this code (based on the original template):
```
### Hi there 👋

<!-- raw html -->


#### 👷 Check out what I'm currently working on
{{range recentContributions 10}}
- [{{.Repo.Name}}]({{.Repo.URL}}) - {{.Repo.Description}} ({{humanize .OccurredAt}})
{{- end}}
....
```

the result is rendered like this:
```
### Hi there 👋




#### 👷 Check out what I'm currently working on

- [jetzlstorfer/plattentests-go](https://github.com/jetzlstorfer/plattentests-go) - creates a spotify playlist based on most recent record reviews from my favourite music website plattentests.de 💿 (today)
...
```

As you can see, the HTML comment is now gone. Therefore I implemented the `comment` function that keeps the comment.

**Comment by jetzlstorfer** [comment]
Provided a way easier solution based on the feedback in #62

**Comment by muesli** [comment]
Thank you for testing & confirming, as well as updating your PR!

**Comment by ansidev** [comment]
@jetzlstorfer @muesli

I don't know how you have tested this PR. However, it doesn't work as described.

Reproduction repository: https://github.com/ansidev/markscribe-test-01

**Comment by muesli** [comment]
Can you be a bit more specific? What isn't working?

**Comment by ansidev** [comment]
> Can you be a bit more specific? What isn't working?

@muesli The latest tag is pointing to v0.6.0.

**Comment by muesli** [comment]
> @muesli The latest tag is pointing to v0.6.0.

Correct. What's the issue?

**Comment by ansidev** [comment]
> > @muesli The latest tag is pointing to v0.6.0.
> 
> Correct. What's the issue?

@muesli v0.6.0 does not include this PR. I guess you should bump the version to v0.6.1.

And please also update the following projects:

- GitHub Actions: https://github.com/muesli/readme-scribe/
- Associate Docker Image: `fribbledom/markscribe` (I guess you don't public the source code because I can't find the source repository)

**Comment by muesli** [comment]
> @muesli v0.6.0 does not include this PR. I guess you should bump the version to v0.6.1.

Sorry, I thought you meant there's an issue with this particular change. It will be part of v0.7.0, sometime soon.

> And please also update the following projects:
> 
>     * GitHub Actions: https://github.com/muesli/readme-scribe/\

What updates do you expect there?

>     * Associate Docker Image: `fribbledom/markscribe` (I guess you don't public the source code because I can't find the source repository)

The `Dockerfile` is in this repo.

**Comment by ansidev** [comment]
> > @muesli v0.6.0 does not include this PR. I guess you should bump the version to v0.6.1.
> 
> Sorry, I thought you meant there's an issue with this particular change. It will be part of v0.7.0, sometime soon.
> 
> > And please also update the following projects:
> > ```
> > * GitHub Actions: https://github.com/muesli/readme-scribe/\
> > ```
> 
> What updates do you expect there?
> 
> > ```
> > * Associate Docker Image: `fribbledom/markscribe` (I guess you don't public the source code because I can't find the source repository)
> > ```
> 
> The `Dockerfile` is in this repo.

@muesli It's OK. I just wait for the new release 😀.

**Comment by jetzlstorfer** [comment]
Is the release planned any time soon @muesli ?

**Pull request merged**
