### PR TITLE
Implement basic GoodReads templates

### PR DESCRIPTION
**Pull request by louis030195**
Basic GoodReads templates (latest reviews and currently reading books) using GoodReads API which requires as repository secrets:
- GOODREADS_TOKEN
- GOODREADS_USER_ID

Added a new dependency: <https://github.com/KyleBanks/goodreads>

Renamed local GitHub "client" to gitHubClient because there could be several API clients

```md
#### 👷 What I'm currently reading
{{range goodReadsCurrentlyReading 5}}
- {{.Book.Title}} - {{.Book.Link}} - {{humanize .DateUpdated}}
{{- end}}


#### 👷 My latest Goodreads reviews
{{range goodReadsReviews 5}}
- {{.Book.Title}} - {{.Book.Link}} - {{.Rating}} - {{humanize .DateUpdated}}
{{- end}}
```

Result:

#### 👷 What I'm currently reading

- The Society of Mind - https://www.goodreads.com/book/show/326790.The_Society_of_Mind - Sat Oct 31 00:04:27 -0700 2020

#### 👷 My latest Goodreads reviews

- Six Easy Pieces: Essentials of Physics By Its Most Brilliant Teacher - https://www.goodreads.com/book/show/5553.Six_Easy_Pieces - 5 - Sat Oct 31 00:08:55 -0700 2020
- L&#39;Ingénu - https://www.goodreads.com/book/show/289382.L_Ing_nu - 4 - Tue Oct 20 23:28:27 -0700 2020
- The Red Queen: Sex and the Evolution of Human Nature - https://www.goodreads.com/book/show/16176.The_Red_Queen - 5 - Mon Sep 21 01:15:21 -0700 2020
- Cosmos - https://www.goodreads.com/book/show/55030.Cosmos - 5 - Mon Jul 20 05:19:10 -0700 2020
- Leonardo&#39;s Notebooks - https://www.goodreads.com/book/show/24096.Leonardo_s_Notebooks - 5 - Mon Jun 15 11:40:45 -0700 2020

---

Let me know if there is anything to clean up or anything wrong.

### CODE REVIEW

**Comment by muesli** [comment]
Code looks good, but I noticed it's not formatted with `gofmt`. Please do that, as it ensures maintaining a consistent coding style. I can highly recommend setting this up to be automatically executed when you save your code in your editor. It really makes developing in Go so much more convenient.

**Comment by louis030195** [comment]
@muesli yep, done, thanks for the tip !

**Comment by muesli** [comment]
Thank you @louis030195!

**Comment by louis030195** [comment]
Now I'm not sure how to make https://github.com/muesli/readme-scribe use this new feature ?

**Comment by louis030195** [comment]
I guess your Docker image is hand-pushed ? Might implement the automated build & push github action someday, example: <https://github.com/PrismarineJS/flying-squid/blob/master/.github/workflows/docker.yml>

**Comment by muesli** [comment]
@louis030195 Correct, I'll have to push a new markscribe release & Docker image. Will take care of that tonight! Just a tiny bit of patience :smiley:

**Comment by muesli** [comment]
Sorry, took a bit longer than anticipated. However, a new image has just been pushed! Let me know if everything works as anticipated!

**Comment by louis030195** [comment]
awesome https://louis030195.com
image

**Comment by louis030195** [comment]
btw might document the fact that you have to set env var for development (tokens) to run the code (kinda obvious but I had to think a bit since the error isn't clear :p)

**Pull request merged**
